the_project:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', '127.0.0.1') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASS') }}"
      dbname: "{{ env_var('DB_NAME', 'postgres') }}"
      schema: "{{ env_var('DB_SCHEMA', 'public') }}"
      threads: 1
  target: dev
