name: "the_project"
version: "1.0.0"
profile: "the_project"

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  the_project:
    +schema: stg
    ref_countries:
      +column_types:
        code: char(2)
        name: varchar(100)

models:
  the_project:
    staging:
      +materialized: table
      schema: stg
    marts:
      +materialized: table
      schema: marts

tests:
  +store_failures: true
