name: "the_project"
version: "1.0.0"
profile: "the_project"

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  the_project:
    +schema: "{{ env_var('DB_SCHEMA_STG', 'stg') }}"
    ref_countries:
      +column_types:
        code: char(2)
        name: varchar(100)

models:
  the_project:
    staging:
      +materialized: incremental
      incremental_strategy: append
      schema: "{{ env_var('DB_SCHEMA_STG', 'stg') }}"
    marts:
      +materialized: incremental
      incremental_strategy: append
      schema: "{{ env_var('DB_SCHEMA_MART', 'mart') }}"

tests:
  +store_failures: true
